---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by koerriva.
--- DateTime: 2022/6/26 1:34
---

entities = {}

function getTransform(entity)
    return Transform()
end


return entities